model:
  base_learning_rate: 5.0e-5
  target: diff_foley.modules.double_guidance.alignment_classifier_metric.Alignment_Classifier_metric
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    timesteps: 1000
    scale_factor: 0.18215
    first_stage_key: spec
    monitor: val/bce_loss

    first_stage_config:
      target: diff_foley.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    classifier_config:
      target: diff_foley.modules.double_guidance.alignment_backbone.Classifier_Backbone
      params:
        image_size: 32      # unused
        in_channels: 4
        out_channels: 1
        model_channels: 128
        attention_resolutions: [2, 4]
        num_res_blocks: 1
        channel_mult: [1, 2, 2]
        num_heads: 8
        use_spatial_transformer: True
        transformer_depth: 1
        context_dim: 512
        use_checkpoint: True
        legacy: False


    cond_stage_config:
      target: diff_foley.modules.cond_stage.video_feat_encoder.Video_Feat_Encoder_Posembed
      params:
        origin_dim: 512
        embed_dim: 512
        seq_len: 40


data_eval_metric:
  target: main.DataModuleFromConfig
  batch_size: 64
  params:
    num_workers: 8
    batch_size: 64
    wrap: True
    validation:
      target: dataset.VGGSound_audio_video_spec_fullset_Dataset_Valid_Infer
      params:
        eval_dataset_path: # Path to Generate Folder
        data_dir: /dataset/VGGSound
        split_txt_path: /dataset/VGGSound
        feat_type: CAVP_feat
        sr: 16000
        duration: 10
        truncate: 131072
        fps: 4
