X3D:
  WIDTH_FACTOR: 2.0
  DEPTH_FACTOR: 2.2
  BOTTLENECK_FACTOR: 2.25
  DIM_C5: 2048
  DIM_C1: 12
DATA:
  NUM_FRAMES: 16
  TRAIN_CROP_SIZE: 224
  INPUT_CHANNEL_NUM: [3]
RESNET:
  ZERO_INIT_FINAL_BN: True
  TRANS_FUNC: x3d_transform
  STRIDE_1X1: False
BN:
  NORM_TYPE: "batchnorm"
MODEL:
  OUT_DIM: 512
  ARCH: x3d
  DROPOUT_RATE: 0.5